### ISSUE TITLE
Hello, I am experiencing a bug for the popup menu on initial render.

### ISSUE THREAD

**Issue by kcimartinez** [Muneyy/rest-countries-api-next#7]
Hello, I am experiencing a bug for the popup menu on initial render. 
![image](https://github.com/Muneyy/rest-countries-api-next/assets/107381315/a44bf473-9df6-4dfa-9d53-bb26436c21ab)

The background of the component is transparent even if I explicitly set the background-color. The bug is fixed (background-color is correct) only after dark mode is toggled.

_Originally posted by @Muneyy in https://github.com/Muneyy/rest-countries-api-next/issues/5#issuecomment-1959391047_

**Comment by bzgaspar** [comment]
Your bg color for menu is set with a variable from your global style, which is set to a data theme 'light' / 'dark'. Therefore, in your initial render data-theme does not have a default value and your variable is not yet defined.
